### ISSUE TITLE
 Error executing FreeMarker template

### ISSUE THREAD

**Issue by haodedong** [ruibaby/casper-halo#1]
你好，我在导入模版的时候，出现了以下的错误
2018-11-11 09:41:09.121 ERROR 49045 --- [ XNIO-2 task-31] io.undertow.request                      : UT005023: Exception handling request to /admin/themes/options

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core._MiscTemplateException: Template importing failed (for parameter value "/common/macro/theme_option_marco.ftl"):
Template not found for name "common/macro/theme_option_marco.ftl".
The name was interpreted by this TemplateLoader: MultiTemplateLoader(loader1 = FileTemplateLoader(baseDir="/Users/hdd/workSpace/halo-blogs/target/classes/templates", canonicalBasePath="/Users/hdd/workSpace/halo-blogs/target/classes/templates/"), loader2 = ClassTemplateLoader(resourceLoaderClass=org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer, basePackagePath="" /* relatively to resourceLoaderClass pkg */)).

FTL stack trace ("~" means nesting-related):
	- Failed at: #import "/common/macro/theme_option_m...  [in template "themes/casper-halo-1.3/module/options.ftl" at line 1, column 1]

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]

恳请 帮忙看一下，万分感谢

**Comment by ruibaby** [comment]
升级一下halo版本。
